name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Vielen Dank für deinen ersten Commit/Pull! Leider hat er Fehler!' first issue"
        pr-message: "Vielen Dank für deinen ersten Commit/Pull!' first pull request"
